services:
  cosmicweightconverter:
    image: ${DOCKER_REGISTRY-}cosmicweightconverter
    build:
      context: .
      dockerfile: CosmicWeightConverter/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - cosmicweightconverter-network
networks:
    cosmicweightconverter-network:
        driver: bridge
