name: CI Pipeline for Cosmic Weight Converter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"
      - name: Restore dependencies
        run : dotnet restore CosmicWeightConverter/CosmicWeightConverter.csproj
      - name: Build
        run: dotnet build --no-restore CosmicWeightConverter/CosmicWeightConverter.csproj --configuration Release
      - name: Set up short commit SHA
        id: commit_sha
        run: echo "SHA_SHORT=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_OUTPUT
      - name: Build and Tag Docker Image
        run: |
          docker build -t abdalrbashir/cosmic-weight-converter:${{ steps.commit_sha.outputs.SHA_SHORT }} -f CosmicWeightConverter/Dockerfile .
      - name: Scan Docker Imgge (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: abdalrbashir/cosmic-weight-converter:${{ steps.commit_sha.outputs.SHA_SHORT }}
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
          scanners: 'vuln'
          format: 'table'
